import uuid
from datetime import datetime

from sqlalchemy import BigInteger, DateTime, ForeignKey, String, Text, UniqueConstraint, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class ConsentimientoFirmante(Base):
    """Immutable human-signature evidence captured before finalization."""

    __tablename__ = "consentimiento_firmantes"
    __table_args__ = (
        UniqueConstraint(
            "consentimiento_id", "tipo", "orden", name="uq_consentimiento_firmante_tipo_orden"
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, server_default=text("gen_random_uuid()")
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id"), nullable=False, index=True
    )
    consentimiento_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("consentimientos.id"), nullable=False, index=True
    )
    tipo: Mapped[str] = mapped_column(String(20), nullable=False)
    orden: Mapped[int] = mapped_column(nullable=False, server_default="0")
    nombre: Mapped[str] = mapped_column(String(200), nullable=False)
    relacion_paciente: Mapped[str | None] = mapped_column(String(120))
    motivo_representacion: Mapped[str | None] = mapped_column(Text)
    firma_base64: Mapped[str] = mapped_column(Text, nullable=False)
    firma_sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    firmado_en: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
    creado_en: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )


class ConsentimientoDocumentoFinal(Base):
    """The single immutable S3 PDF generated by final consent signature."""

    __tablename__ = "consentimiento_documentos_finales"
    __table_args__ = (
        UniqueConstraint("consentimiento_id", name="uq_consentimiento_documento_final"),
        UniqueConstraint("s3_key", name="uq_consentimiento_documento_s3_key"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, server_default=text("gen_random_uuid()")
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id"), nullable=False, index=True
    )
    consentimiento_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("consentimientos.id"), nullable=False, index=True
    )
    s3_bucket: Mapped[str] = mapped_column(String(255), nullable=False)
    s3_key: Mapped[str] = mapped_column(String(500), nullable=False)
    s3_version_id: Mapped[str | None] = mapped_column(String(200))
    s3_etag: Mapped[str | None] = mapped_column(String(100))
    contenido_sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    content_type: Mapped[str] = mapped_column(String(100), nullable=False, server_default="application/pdf")
    size_bytes: Mapped[int] = mapped_column(BigInteger, nullable=False)
    creado_en: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )


class ConsentimientoRevocacion(Base):
    """Immutable revocation event; the signed consent row is never changed."""

    __tablename__ = "consentimiento_revocaciones"
    __table_args__ = (
        UniqueConstraint("consentimiento_id", name="uq_consentimiento_revocacion"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, server_default=text("gen_random_uuid()")
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("tenants.id"), nullable=False, index=True
    )
    consentimiento_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("consentimientos.id"), nullable=False, index=True
    )
    motivo: Mapped[str] = mapped_column(Text, nullable=False)
    actor_nombre: Mapped[str] = mapped_column(String(200), nullable=False)
    actor_tipo: Mapped[str] = mapped_column(String(30), nullable=False, server_default="medico")
    revocado_en: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()")
    )
