"""Add password_hash to tenants

Revision ID: 2443906c3ca8
Revises: ab082dc48b3f
Create Date: 2026-06-04 20:38:16.872042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2443906c3ca8'
down_revision: Union[str, None] = 'ab082dc48b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'password_hash')
    # ### end Alembic commands ###
