"""add citas model

Revision ID: 54bfed9c5a72
Revises: fee2c45ae41a
Create Date: 2026-06-17 00:54:44.420629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54bfed9c5a72'
down_revision: Union[str, None] = 'fee2c45ae41a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=50), server_default='Programada', nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modificado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citas_paciente_id'), 'citas', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_citas_tenant_id'), 'citas', ['tenant_id'], unique=False)
    
    # --- RLS Enforcement ---
    op.execute("ALTER TABLE citas ENABLE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation_policy ON citas
        USING (tenant_id = current_setting('app.current_tenant')::uuid)
    """)
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON citas TO medrecord_app")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citas_tenant_id'), table_name='citas')
    op.drop_index(op.f('ix_citas_paciente_id'), table_name='citas')
    op.drop_table('citas')
    # ### end Alembic commands ###
