"""Initial schema

Revision ID: 5a379e6d412d
Revises: 
Create Date: 2026-06-02 14:16:35.141237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a379e6d412d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tabla', sa.String(length=50), nullable=False),
    sa.Column('registro_id', sa.UUID(), nullable=False),
    sa.Column('accion', sa.String(length=10), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('ip_origen', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('datos_antes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('datos_despues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exito', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('error_detalle', sa.Text(), nullable=True),
    sa.CheckConstraint("accion IN ('SELECT', 'INSERT', 'UPDATE', 'DELETE')", name='audit_log_accion_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre_medico', sa.String(length=200), nullable=False),
    sa.Column('cedula', sa.String(length=20), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.Column('rfc', sa.String(length=13), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('plan', sa.String(length=20), server_default='basico', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cedula'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=200), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('sexo', sa.String(length=10), nullable=False),
    sa.Column('curp', sa.String(length=18), nullable=True),
    sa.Column('entidad_nacimiento', sa.String(length=50), nullable=True),
    sa.Column('nacionalidad', sa.String(length=50), server_default='Mexicana', nullable=True),
    sa.Column('ocupacion', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('aseguradora', sa.String(length=100), nullable=True),
    sa.Column('num_poliza', sa.String(length=50), nullable=True),
    sa.Column('domicilio_cifrado', postgresql.BYTEA(), nullable=True),
    sa.Column('creado_por', sa.UUID(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modificado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sexo IN ('M', 'F', 'X')", name='pacientes_sexo_check'),
    sa.ForeignKeyConstraint(['creado_por'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'curp', name='uq_paciente_tenant')
    )
    op.create_index(op.f('ix_pacientes_curp'), 'pacientes', ['curp'], unique=False)
    op.create_index(op.f('ix_pacientes_tenant_id'), 'pacientes', ['tenant_id'], unique=False)
    op.create_table('tenant_keys',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('encrypted_dek', postgresql.BYTEA(), nullable=False),
    sa.Column('kms_key_id', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('avisos_privacidad',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('version_aviso', sa.String(length=10), server_default='1.0', nullable=False),
    sa.Column('aceptado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('consentimiento_datos_sensibles', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'paciente_id', 'version_aviso')
    )
    op.create_index(op.f('ix_avisos_privacidad_paciente_id'), 'avisos_privacidad', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_avisos_privacidad_tenant_id'), 'avisos_privacidad', ['tenant_id'], unique=False)
    op.create_table('expedientes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('folio', sa.String(length=20), nullable=False),
    sa.Column('antecedentes_cifrado', postgresql.BYTEA(), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default='activo', nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'folio', name='uq_folio_tenant')
    )
    op.create_index(op.f('ix_expedientes_paciente_id'), 'expedientes', ['paciente_id'], unique=False)
    op.create_index(op.f('ix_expedientes_tenant_id'), 'expedientes', ['tenant_id'], unique=False)
    op.create_table('consentimientos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('expediente_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('hash_documento', sa.String(length=64), nullable=True),
    sa.Column('firmado_por', sa.String(length=200), nullable=True),
    sa.Column('firmado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consentimientos_expediente_id'), 'consentimientos', ['expediente_id'], unique=False)
    op.create_index(op.f('ix_consentimientos_tenant_id'), 'consentimientos', ['tenant_id'], unique=False)
    op.create_table('notas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('expediente_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tipo_nota', sa.String(length=30), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('diagnostico_cie10', sa.String(length=10), nullable=True),
    sa.Column('signos_vitales', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('firma_digital', postgresql.BYTEA(), nullable=True),
    sa.Column('firma_hash_contenido', sa.String(length=64), nullable=True),
    sa.Column('firma_kms_key_id', sa.String(length=200), nullable=True),
    sa.Column('firma_algoritmo', sa.String(length=30), server_default='ECDSA_SHA_256', nullable=True),
    sa.Column('firmado_por', sa.UUID(), nullable=True),
    sa.Column('firmado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('es_editable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('medico_nombre', sa.String(length=200), nullable=True),
    sa.Column('medico_cedula', sa.String(length=20), nullable=True),
    sa.Column('medico_especialidad', sa.String(length=100), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.UUID(), nullable=True),
    sa.CheckConstraint("tipo_nota IN ('ingreso', 'evolucion', 'egreso', 'interconsulta', 'referencia', 'traslado', 'quirurgica', 'anestesiologia', 'enfermeria', 'urgencias', 'historia_clinica')", name='notas_tipo_nota_check'),
    sa.ForeignKeyConstraint(['creado_por'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['expediente_id'], ['expedientes.id'], ),
    sa.ForeignKeyConstraint(['firmado_por'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notas_expediente_id'), 'notas', ['expediente_id'], unique=False)
    op.create_index(op.f('ix_notas_tenant_id'), 'notas', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_notas_tipo_nota'), 'notas', ['tipo_nota'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notas_tipo_nota'), table_name='notas')
    op.drop_index(op.f('ix_notas_tenant_id'), table_name='notas')
    op.drop_index(op.f('ix_notas_expediente_id'), table_name='notas')
    op.drop_table('notas')
    op.drop_index(op.f('ix_consentimientos_tenant_id'), table_name='consentimientos')
    op.drop_index(op.f('ix_consentimientos_expediente_id'), table_name='consentimientos')
    op.drop_table('consentimientos')
    op.drop_index(op.f('ix_expedientes_tenant_id'), table_name='expedientes')
    op.drop_index(op.f('ix_expedientes_paciente_id'), table_name='expedientes')
    op.drop_table('expedientes')
    op.drop_index(op.f('ix_avisos_privacidad_tenant_id'), table_name='avisos_privacidad')
    op.drop_index(op.f('ix_avisos_privacidad_paciente_id'), table_name='avisos_privacidad')
    op.drop_table('avisos_privacidad')
    op.drop_table('tenant_keys')
    op.drop_index(op.f('ix_pacientes_tenant_id'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_curp'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
