"""ponytail: beta v1 models

Revision ID: a6651e6fe6c3
Revises: 4f4145428368
Create Date: 2026-06-27 22:00:46.886515

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a6651e6fe6c3'
down_revision: Union[str, None] = '4f4145428368'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cie10',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_cie10_category'), 'cie10', ['category'], unique=False)
    op.create_index(op.f('ix_cie10_description'), 'cie10', ['description'], unique=False)
    op.create_table('recetas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('nota_id', sa.UUID(), nullable=False),
    sa.Column('medicamentos', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('indicaciones_generales', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nota_id'], ['notas.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recetas_nota_id'), 'recetas', ['nota_id'], unique=False)
    op.create_index(op.f('ix_recetas_tenant_id'), 'recetas', ['tenant_id'], unique=False)
    op.add_column('notas', sa.Column('motivo_consulta', sa.Text(), nullable=True))
    op.add_column('notas', sa.Column('exploracion_fisica', sa.Text(), nullable=True))
    op.add_column('notas', sa.Column('plan_tratamiento', sa.Text(), nullable=True))
    op.add_column('notas', sa.Column('estado', sa.String(length=20), server_default='draft', nullable=False))
    op.drop_column('notas', 'firma_kms_key_id')
    op.add_column('pacientes', sa.Column('contacto_emergencia', sa.String(length=200), nullable=True))
    op.add_column('pacientes', sa.Column('telefono_emergencia', sa.String(length=20), nullable=True))
    op.add_column('pacientes', sa.Column('tipo_sangre', sa.String(length=5), nullable=True))
    op.add_column('pacientes', sa.Column('alergias', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'alergias')
    op.drop_column('pacientes', 'tipo_sangre')
    op.drop_column('pacientes', 'telefono_emergencia')
    op.drop_column('pacientes', 'contacto_emergencia')
    op.add_column('notas', sa.Column('firma_kms_key_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('notas', 'estado')
    op.drop_column('notas', 'plan_tratamiento')
    op.drop_column('notas', 'exploracion_fisica')
    op.drop_column('notas', 'motivo_consulta')
    op.drop_index(op.f('ix_recetas_tenant_id'), table_name='recetas')
    op.drop_index(op.f('ix_recetas_nota_id'), table_name='recetas')
    op.drop_table('recetas')
    op.drop_index(op.f('ix_cie10_description'), table_name='cie10')
    op.drop_index(op.f('ix_cie10_category'), table_name='cie10')
    op.drop_table('cie10')
    # ### end Alembic commands ###
