"""Change usuario_id to string for clerk

Revision ID: b0525c4b9d00
Revises: 2443906c3ca8
Create Date: 2026-06-12 01:04:14.343094

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0525c4b9d00"
down_revision: Union[str, None] = "2443906c3ca8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_log",
        "usuario_id",
        existing_type=sa.UUID(),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_audit_log_usuario_id"), "audit_log", ["usuario_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_log_usuario_id"), table_name="audit_log")
    op.alter_column(
        "audit_log",
        "usuario_id",
        existing_type=sa.String(length=100),
        type_=sa.UUID(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
