"""fix: restore firma_kms_key_id

Revision ID: e937940d8de9
Revises: a6651e6fe6c3
Create Date: 2026-06-27 22:01:17.908834

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e937940d8de9'
down_revision: Union[str, None] = 'a6651e6fe6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notas', sa.Column('firma_kms_key_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notas', 'firma_kms_key_id')
    # ### end Alembic commands ###
